/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#d6e3ff',
        'secondary-fixed': '#ffdeaa',
        'inverse-primary': '#b5c7ea',
        'on-error-container': '#93000a',
        'on-primary-fixed-variant': '#364764',
        'surface-tint': '#4d5f7d',
        'surface': '#fcf9f8',
        'on-secondary-container': '#755100',
        'primary-fixed-dim': '#b5c7ea',
        'primary-container': '#0b1f3a',
        'surface-container-highest': '#e5e2e1',
        'on-tertiary-container': '#a87e59',
        'primary': '#000615',
        'surface-container-high': '#eae7e7',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'error': '#ba1a1a',
        'surface-dim': '#dcd9d9',
        'secondary': '#7d5700',
        'tertiary-container': '#321800',
        'inverse-on-surface': '#f3f0ef',
        'on-primary-container': '#7587a7',
        'on-surface': '#1c1b1b',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#313030',
        'on-tertiary': '#ffffff',
        'on-background': '#1c1b1b',
        'surface-container': '#f0eded',
        'surface-container-low': '#f6f3f2',
        'surface-variant': '#e5e2e1',
        'secondary-container': '#ffc55f',
        'error-container': '#ffdad6',
        'tertiary-fixed': '#ffdcc1',
        'on-surface-variant': '#44474d',
        'outline-variant': '#c4c6ce',
        'on-primary': '#ffffff',
        'secondary-fixed-dim': '#f5bd58',
        'tertiary': '#0d0400',
        'outline': '#75777e',
        'on-secondary-fixed-variant': '#5f4100',
        'on-tertiary-fixed-variant': '#613f20',
        'surface-bright': '#fcf9f8',
        'on-primary-fixed': '#071c36',
        'on-secondary-fixed': '#271900',
        'tertiary-fixed-dim': '#eebd94',
        'on-tertiary-fixed': '#2e1500',
        'background': '#fcf9f8',
        'gold-accent': '#D9A441',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-gap': '120px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'unit': '8px',
        'container-max': '1280px',
        'gutter': '32px',
      },
      fontFamily: {
        'display-xl': ['Playfair Display', 'serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'subheading-md': ['Manrope', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'body-rt': ['Inter', 'sans-serif'],
        'button-text': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'display-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'subheading-md': ['20px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'body-rt': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'button-text': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
